### PR TITLE
0.2.0

### PR DESCRIPTION
**Pull request by aidenprice**

### CODE REVIEW

**Comment by nghialv** [comment]
@aidenprice Thank you for your pull request. Could you please send PR to this repository? (Because this `examples` repository is synced with the examples directory of `pipe` repository.)

https://github.com/pipe-cd/pipe/tree/master/examples

**Comment by aidenprice** [comment]
Sorry, I made this PR in error while following the QuickStart tutorial. Clicked ahead too quickly.

If I could delete the PR entirely I would.

Sorry again and thanks.

**Comment by nghialv** [comment]
No problem. Thank you for your interest and trying PipeCD. 👍

**Comment by aidenprice** [comment]
You're welcome, and I'm actually really interested in PipeCD. Hoping to use it for Kubernetes clusters on site and one day on the edge.

**Comment by nghialv** [comment]
Thank you for your kind words. ❤️ 
Please raise issues in the [pipe](https://github.com/pipe-cd/pipe) repository if you want any help from PipeCD team.
Thanks.

**Pull request closed without merging**
